name: Cross Platform Action
description: Provides cross platform runner
author: Jacob Carlborg
inputs:
  run:
    required: true
    description: |
      Runs command-line programs using the operating system's shell.
      This will be executed inside the virtual machine.
  operating_system:
    required: true
    description: The type of operating system to run the job on
  architecture:
    required: false
    description: The architecture of the operating system.
    default: x86-64
  version:
    required: true
    description: The version of the operating system to use
  shell:
    required: false
    description: |
      The shell to use to execute the commands. Defaults to the default shell
      for the given operating system.
    default: default
  environment_variables:
    required: false
    description: |
      A list of environment variables to forward to the virtual machine.
      The list should be separated with spaces.
    default: ''
  memory:
    required: false
    description: The amout of memory for the virtual machine
  cpu_count:
    required: false
    description: The number of CPU cores for the virtual machine
  hypervisor:
    required: false
    description: The hypervisor to use when  starting the virtual machine
  image_url:
    required: false
    description: URL for running the action with a custom image.
    default: ''

runs:
  using: node16
  main: dist/index.js

branding:
  icon: play-circle
  color: green
